# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-10-04 02:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64, verbose_name='标题')),
                ('url', models.CharField(max_length=256, verbose_name='链接')),
                ('news_type', models.CharField(max_length=64, verbose_name='新闻类型')),
                ('images', models.CharField(default='', max_length=512, verbose_name='图片')),
                ('platform', models.URLField(blank=True, default='', null=True, verbose_name='平台')),
                ('creation_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '新闻资讯',
                'verbose_name_plural': '新闻资讯',
            },
        ),
    ]
