# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-10-22 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='hot_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='新闻热度'),
        ),
    ]
