# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-11-15 14:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_news_hot_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=64, verbose_name='豆瓣id')),
                ('name', models.CharField(max_length=128, verbose_name='书名称')),
                ('price', models.CharField(max_length=128, verbose_name='价格')),
                ('publish', models.CharField(max_length=256, verbose_name='出版社')),
                ('score', models.IntegerField(max_length=5, verbose_name='评分')),
                ('cover', models.CharField(max_length=256, verbose_name='封面')),
                ('url', models.CharField(max_length=256, verbose_name='链接')),
                ('Introduction', models.CharField(max_length=512, verbose_name='简介')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
            },
        ),
        migrations.CreateModel(
            name='BookTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=64, verbose_name='标签')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '图书标签',
                'verbose_name_plural': '图书标签',
            },
        ),
    ]
