# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-11-15 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tag',
            field=models.ManyToManyField(to='crm.BookTag'),
        ),
    ]
