# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-11-15 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_book_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tag',
            field=models.ManyToManyField(related_name='books', to='crm.BookTag', verbose_name='标签'),
        ),
    ]
