# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-11-15 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20181115_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='score',
            field=models.IntegerField(default=0, verbose_name='评分'),
        ),
    ]
