# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-11-16 14:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20181115_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAndLInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='c&l信息')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': 'c&l信息',
                'verbose_name': 'c&l信息',
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='score',
            field=models.FloatField(default=0, verbose_name='评分'),
        ),
    ]
