# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-11-16 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20181116_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktag',
            name='check',
            field=models.CharField(default='0', max_length=8, verbose_name='是否意见检测'),
        ),
    ]
