# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-01-10 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.CharField(max_length=500, verbose_name='开盘')),
                ('high', models.CharField(max_length=500, verbose_name='最高')),
                ('low', models.CharField(max_length=500, verbose_name='最低')),
                ('close', models.CharField(max_length=500, verbose_name='收盘')),
                ('chg', models.CharField(max_length=500, verbose_name='涨跌额度')),
                ('percent', models.CharField(max_length=500, verbose_name='涨跌幅')),
                ('turnoverrate', models.CharField(max_length=500, verbose_name='换手率')),
                ('volume', models.CharField(max_length=500, verbose_name='成交额')),
                ('timestamp', models.CharField(max_length=500, verbose_name='时间')),
            ],
            options={
                'verbose_name_plural': '股票',
                'verbose_name': '股票',
                'db_table': 'Stock',
            },
        ),
    ]
