# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-01-13 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='high_start',
            field=models.BooleanField(default=False, verbose_name='是否是高开'),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_name',
            field=models.CharField(blank=True, default='上证', max_length=500, null=True, verbose_name='股票名称'),
        ),
    ]
