# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-01-13 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_stock_yesterday_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='date_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
