# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-01-16 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_stock_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='close_minus_open',
            field=models.CharField(default='', max_length=500, verbose_name='收盘减去开盘'),
            preserve_default=False,
        ),
    ]
